### ISSUE TITLE
feat: Importing resolvers into the Apollo server

### ISSUE THREAD

**Issue by antiyro** [snapshot-labs/checkpoint#164]
I have to set up an Apollo server to be able to transmit it to a Lambda serverless Function. 
By following the Apollo setup I end up with the simple following code: 

```js
import { ApolloServer } from '@apollo/server';
import { startServerAndCreateLambdaHandler } from '@as-integrations/aws-lambda'; //highlight-line

const typeDefs = `#graphql
  type Query {
    hello: String
  }
`;

const resolvers = {
  Query: {
    hello: () => 'world',
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
});

// This final export is important!
export const graphqlHandler = startServerAndCreateLambdaHandler(server);
```

Now I need to setup the schema and the resolvers by importing them from Checkpoint. 
For the schema I can do it easily with : `checkpoint.getSchema()` or even by importing the `schema.gql` file directly.
For the resolvers @Sekhmet pointed out using :

```js
const resolvers = Object.fromEntries(
  Object.entries(checkpoint.getSchema().getQueryType()?.getFields() ?? {}).map(([k, v]) => [
    k,
    v.resolve
  ]) 
);
```
Which leads me to the following error :

```
Type '{ [k: string]: GraphQLFieldResolver<any, any, any, unknown> | undefined; }' is not assignable to type 'IResolvers<any, any, Record<string, any>, any> | IResolvers<any, any, Record<string, any>, any>[] | undefined'.
  Type '{ [k: string]: GraphQLFieldResolver<any, any, any, unknown> | undefined; }' is missing the following properties from type 'IResolvers<any, any, Record<string, any>, any>[]': length, pop, push, concat, and 29 more.ts(2322)
```
Could it be possible to easily export the Resolvers trough Checkpoint?

**Comment by Sekhmet** [comment]
> For the schema I can do it easily with : checkpoint.getSchema() or even by importing the schema.gql file directly.

Can't you use this format from [support PR](https://github.com/snapshot-labs/checkpoint/pull/162)?

```js
const server = new ApolloServer({
  schema: checkpoint.getSchema()
});
```
