### ISSUE TITLE
Allow for configuration without specific address

### ISSUE THREAD

**Issue by rzmahmood** [snapshot-labs/checkpoint#62]
Hi all,

I have a use case where I want to view all events of a particular type, regardless of the contract address. This is useful for standards-based events, for example, transfer events of ERC20s. I was wondering if this is something checkpoint can support?

Cheers

**Comment by bonustrack** [comment]
@rzmahmood We've just release a new version `v0.1.0-beta.5` with 2 new params for the config file `tx_fn` and `start`. Using `tx_fn` allow you to trigger a writer function for all the transactions, `start` define where to start to trigger `tx_fn` writer. Here is an example of config:

```json
{
  "network": "goerli-alpha",
  "start": 276000,
  "tx_fn": "handleTx",
  "sources": []
}
```
In the writer
```ts
export async function handleTx({ block, tx, receipt, mysql }) {
  // Do stuff
}
```
