### ISSUE TITLE
Sync pending block

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/checkpoint#63]
On the sequencer REST API we can query for pending block, example:
https://alpha4.starknet.io/feeder_gateway/get_block?blockNumber=pending
This is helpful if we want to avoid waiting block time (2h currently on mainnet) to sync new events. Currently there isn't any reorg and the order of the tx wont change on the pending block. It can happen in very rare case that a tx is visible in the pending block but got rejected later on, this can happen if the tx computation depend on the block number

**Comment by Sekhmet** [comment]
Same as https://github.com/snapshot-labs/checkpoint/issues/151 I think.
