### ISSUE TITLE
@snapshot-labs/checkpoint has no exported member named CheckpointWriter

### ISSUE THREAD

**Issue by khelil** [snapshot-labs/checkpoint#89]
Hi all,

Trying to launch the project for the first time.

```
TSError: ⨯ Unable to compile TypeScript:
src/writers.ts:1:10 - error TS2724: '"@snapshot-labs/checkpoint"' has no exported member named 'CheckpointWriter'. Did you mean 'CheckpointWriters'?
```

Any idea ?

**Comment by bonustrack** [comment]
@khelil Which version of checkpoint to you use? The latest one v0.1.0-beta.4 should fix that issue

**Comment by khelil** [comment]
Thank you @bonustrack tried the last version, but `yarn dev` command don't work anymore ? i see the command is missing in the `package.json`.  How can i launch the GraphQL interface for that version ?

**Comment by bonustrack** [comment]
Maybe you are looking on checkpoint repository? The command is here: https://github.com/snapshot-labs/checkpoint-template/blob/master/package.json#L11 checkpoint repository is the library it doesn't have a `dev` script.

**Comment by khelil** [comment]
arf ok i was confused, got it ! Thank you for your help @bonustrack
